Fix control points for `line` command
johannes-wolf/typst-canvas pull request #9
Opened 2023-04-17 22:43 UTC by fenjalien

You currently can't use Bezier curves with the `line` command even though its drawn by Typst's `path`. 

This PR solves this by checking if the first element of a vector is an array whenever an operation is to be performed on it, if so the operation is applied to each vector in the array. `apply-transform` and the final translation are also not applied to control points, this fixes the fact that control points are supposed to be relative but any scale or rotation would break them.

As a side note @johannes-wolf you may want to switch to using squash commits instead of merge.

2023-04-17 23:01 UTC, johannes-wolf requested changes
One problem with (typst native) curves is, that we are not able to determine their bounding box to correctly resize the canvas.

I also think, the control points have to be transformed along with their path vertices.

2023-04-17 23:01 UTC, johannes-wolf commented on canvas.typ
> +        return vec.map(slice_vec)
This function is missing from the PR.

2023-04-17 23:08 UTC, fenjalien commented
To give an example of why control points shouldn't be translated along with the vertex:

The path
```typst
#path(
  ((0pt,-20pt), (0pt,0pt), (20pt, 0pt)),
  (20pt,0pt),
  ((0pt,20pt), (20pt,0pt), (0pt, 0pt)),
)
```
produces
![image](https://user-images.githubusercontent.com/34489450/232628805-aa13a6a4-3e2c-421b-9851-b1b042d64656.png)

to translate the path `10pt` to the right, translate only the vertices
```typst
#path(
  ((10pt,-20pt), (0pt,0pt), (20pt, 0pt)),
  (30pt,0pt),
  ((10pt,20pt), (20pt,0pt), (0pt, 0pt)),
)
```
which produces the same image as above. If you also translate the control points
```typst
#path(
  ((10pt,-20pt), (10pt,0pt), (30pt, 0pt)),
  (30pt,0pt),
  ((10pt,20pt), (30pt,0pt), (10pt, 0pt)),
)
```
produces 
![image](https://user-images.githubusercontent.com/34489450/232629175-3aef1dd7-350b-4ba4-be0c-c101b3d69e29.png)
which is incorrect.

2023-04-17 23:10 UTC, fenjalien commented on canvas.typ
> +        return vec.map(slice_vec)
oops missed that

2023-04-17 23:13 UTC, fenjalien commented
Actually scaling and rotation transforms might be okay, it would just be translations?

2023-04-18 00:02 UTC, johannes-wolf commented
I would like to close this in favour of #10 
Reasons:
- With a custom impl. we get correct sizing behaviour of the canvas
- Passing control-points in arrays insides vectors feels hacky
- We will be able to calculate a given bezier point for placing objects at paths

2023-04-18 14:39 UTC, johannes-wolf commented
I do use merge commits because they make for a nice history. Cleaning and rebasing should be done to PRs before merging.

2023-04-18 14:40 UTC, closed without merging